# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-global-accelerator
  description: Terraform module to configure AWS Global Accelerator
  homepage: https://cloudposse.com/accelerate
  topics: terraform, compliance, security
